# Generated by Django 2.2.1 on 2019-09-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_number',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='goods_price',
            field=models.FloatField(default=111, verbose_name='商品单价'),
            preserve_default=False,
        ),
    ]
