# Generated by Django 2.2.1 on 2019-10-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_auto_20191010_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
