# Generated by Django 2.2.1 on 2019-09-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0002_auto_20190924_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='type_picture',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
