# Generated by Django 2.2.1 on 2019-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0006_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
