# Generated by Django 2.2.1 on 2019-10-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0007_auto_20191009_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
